### ISSUE TITLE
Aggregate module is not working anymore in pfsense 2.5

### ISSUE THREAD

**Issue by n00n3L** [pfsensible/core#18]
Hi, I just update pfsense to the version 2.5 and the pfsense_aggregate module is not working anymore. This is the trace:

```
TASK [Setup two vlans, three aliases, six rules, four separators, and delete everything else] *************************************************************************
task path: /home/joe/Downloads/ansible/site.yml:37
<172.16.2.15> ESTABLISH PARAMIKO SSH CONNECTION FOR USER: root on PORT 22 TO 172.16.2.15
<172.16.2.15> EXEC /bin/sh -c 'echo ~root && sleep 0'
<172.16.2.15> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /root/.ansible/tmp/ansible-tmp-1613866031.1342916-233072796188740 `" && echo ansible-tmp-1613866031.1342916-233072796188740="` echo /root/.ansible/tmp/ansible-tmp-1613866031.1342916-233072796188740 `" ) && sleep 0'                                                          
Using module file /home/joe/.ansible/collections/ansible_collections/pfsensible/core/plugins/modules/pfsense_aggregate.py
<172.16.2.15> PUT /home/joe/.ansible/tmp/ansible-local-32996drj_mhem/tmp72e5eqva TO /root/.ansible/tmp/ansible-tmp-1613866031.1342916-233072796188740/AnsiballZ_pfsense_aggregate.py                                                                                                                                                      
<172.16.2.15> EXEC /bin/sh -c 'chmod u+x /root/.ansible/tmp/ansible-tmp-1613866031.1342916-233072796188740/ /root/.ansible/tmp/ansible-tmp-1613866031.1342916-233072796188740/AnsiballZ_pfsense_aggregate.py && sleep 0'                                                                                                                      
<172.16.2.15> EXEC /bin/sh -c '/usr/local/bin/python3.7 /root/.ansible/tmp/ansible-tmp-1613866031.1342916-233072796188740/AnsiballZ_pfsense_aggregate.py && sleep 0'
<172.16.2.15> EXEC /bin/sh -c 'rm -f -r /root/.ansible/tmp/ansible-tmp-1613866031.1342916-233072796188740/ > /dev/null 2>&1 && sleep 0'
The full traceback is:
Traceback (most recent call last):
File "/root/.ansible/tmp/ansible-tmp-1613866031.1342916-233072796188740/AnsiballZ_pfsense_aggregate.py", line 102, in <module>
_ansiballz_main()
File "/root/.ansible/tmp/ansible-tmp-1613866031.1342916-233072796188740/AnsiballZ_pfsense_aggregate.py", line 94, in _ansiballz_main
invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
File "/root/.ansible/tmp/ansible-tmp-1613866031.1342916-233072796188740/AnsiballZ_pfsense_aggregate.py", line 40, in invoke_module
runpy.run_module(mod_name='ansible_collections.pfsensible.core.plugins.modules.pfsense_aggregate', init_globals=None, run_name='__main__', alter_sys=True)
File "/usr/local/lib/python3.7/runpy.py", line 205, in run_module
return _run_module_code(code, init_globals, run_name, mod_spec)
File "/usr/local/lib/python3.7/runpy.py", line 96, in _run_module_code
mod_name, mod_spec, pkg_name, script_name)
File "/usr/local/lib/python3.7/runpy.py", line 85, in _run_code
exec(code, run_globals)
File "/tmp/ansible_pfsense_aggregate_payload_s1ipa_5f/ansible_pfsense_aggregate_payload.zip/ansible_collections/pfsensible/core/plugins/modules/pfsense_aggregate.py", line 1096, in <module>                                                                                                                                               
File "/tmp/ansible_pfsense_aggregate_payload_s1ipa_5f/ansible_pfsense_aggregate_payload.zip/ansible_collections/pfsensible/core/plugins/modules/pfsense_aggregate.py", line 1081, in main                                                                                                                                                   
File "/tmp/ansible_pfsense_aggregate_payload_s1ipa_5f/ansible_pfsense_aggregate_payload.zip/ansible_collections/pfsensible/core/plugins/modules/pfsense_aggregate.py", line 618, in __init__                                                                                                                                                
File "/tmp/ansible_pfsense_aggregate_payload_s1ipa_5f/ansible_pfsense_aggregate_payload.zip/ansible_collections/pfsensible/core/plugins/module_utils/vlan.py", line 44, in __init__
File "/tmp/ansible_pfsense_aggregate_payload_s1ipa_5f/ansible_pfsense_aggregate_payload.zip/ansible_collections/pfsensible/core/plugins/module_utils/pfsense.py", line 573, in php
File "/usr/local/lib/python3.7/json/__init__.py", line 348, in loads
return _default_decoder.decode(s)
File "/usr/local/lib/python3.7/json/decoder.py", line 337, in decode
obj, end = self.raw_decode(s, idx=_w(s, 0).end())
File "/usr/local/lib/python3.7/json/decoder.py", line 355, in raw_decode
raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 2 column 1 (char 1)
fatal: [pflab]: FAILED! => {
"changed": false,
"module_stderr": "",
"module_stdout": "Traceback (most recent call last):\r\n  File \"/root/.ansible/tmp/ansible-tmp-1613866031.1342916-233072796188740/AnsiballZ_pfsense_aggregate.py\", line 102, in <module>\r\n    _ansiballz_main()\r\n  File \"/root/.ansible/tmp/ansible-tmp-1613866031.1342916-233072796188740/AnsiballZ_pfsense_aggregate.py\", line 94, in _ansiballz_main\r\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\r\n  File \"/root/.ansible/tmp/ansible-tmp-1613866031.1342916-233072796188740/AnsiballZ_pfsense_aggregate.py\", line 40, in invoke_module\r\n    runpy.run_module(mod_name='ansible_collections.pfsensible.core.plugins.modules.pfsense_aggregate', init_globals=None, run_name='__main__', alter_sys=True)\r\n  File \"/usr/local/lib/python3.7/runpy.py\", line 205, in run_module\r\n    return _run_module_code(code, init_globals, run_name, mod_spec)\r\n  File \"/usr/local/lib/python3.7/runpy.py\", line 96, in _run_module_code\r\n    mod_name, mod_spec, pkg_name, script_name)\r\n  File \"/usr/local/lib/python3.7/runpy.py\", line 85, in _run_code\r\n    exec(code, run_globals)\r\n  File \"/tmp/ansible_pfsense_aggregate_payload_s1ipa_5f/ansible_pfsense_aggregate_payload.zip/ansible_collections/pfsensible/core/plugins/modules/pfsense_aggregate.py\", line 1096, in <module>\r\n  File \"/tmp/ansible_pfsense_aggregate_payload_s1ipa_5f/ansible_pfsense_aggregate_payload.zip/ansible_collections/pfsensible/core/plugins/modules/pfsense_aggregate.py\", line 1081, in main\r\n  File \"/tmp/ansible_pfsense_aggregate_payload_s1ipa_5f/ansible_pfsense_aggregate_payload.zip/ansible_collections/pfsensible/core/plugins/modules/pfsense_aggregate.py\", line 618, in __init__\r\n  File \"/tmp/ansible_pfsense_aggregate_payload_s1ipa_5f/ansible_pfsense_aggregate_payload.zip/ansible_collections/pfsensible/core/plugins/module_utils/vlan.py\", line 44, in __init__\r\n  File \"/tmp/ansible_pfsense_aggregate_payload_s1ipa_5f/ansible_pfsense_aggregate_payload.zip/ansible_collections/pfsensible/core/plugins/module_utils/pfsense.py\", line 573, in php\r\n  File \"/usr/local/lib/python3.7/json/__init__.py\", line 348, in loads\r\n    return _default_decoder.decode(s)\r\nFile \"/usr/local/lib/python3.7/json/decoder.py\", line 337, in decode\r\n    obj, end = self.raw_decode(s, idx=_w(s, 0).end())\r\n  File \"/usr/local/lib/python3.7/json/decoder.py\", line 355, in raw_decode\r\n    raise JSONDecodeError(\"Expecting value\", s, err.value) from None\r\njson.decoder.JSONDecodeError: Expecting value: line 2 column 1 (char 1)\r\n",
"msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
"rc": 1
}
```

Edit: Add error at pfsense gui
```
PHP ERROR: Type: 1, File: Standard input code, Line: 2, Message: Uncaught Error: Call to undefined function is_jumbo_capable() in Standard input code:2
Stack trace:
#0 {main}
thrown @ 2021-02-20 18:45:44
```

**Comment by f-bor** [comment]
This error has been fixed in the upstream repository.

**Comment by MuhammadShaban** [comment]
@f-bor  I'm using version 0.4.1, and I can confirm that the issue is still exists.

**Comment by f-bor** [comment]
Yes, you need to wait until @opoplawski release a new pfSensible package from the upstream repository.

Otherwise, you can still try to build one from there: https://github.com/opoplawski/ansible-pfsense/ (look misc/mkpfsensible)

**Comment by opoplawski** [comment]
I've pushed the latest changes to pfsense/core master.  You should be able to install (with a current (2.10+?) ansible-galaxy) via:
```
ansible-galaxy collection install --force git+https://github.com/pfsensible/core.git
```
I'm going to wait for some more 2.5.0 fixes before pushing a 0.5.0 release.

**Comment by MuhammadShaban** [comment]
@opoplawski Thanks, but the issue still exists for  pfSense plus 21.02
`PHP ERROR: Type: 1, File: Standard input code, Line: 2, Message: Uncaught Error: Call to undefined function is_jumbo_capable() in Standard input code:2`

**Comment by opoplawski** [comment]
@MuhammadShaban can you paste the output of `pkg-static info` from your pfSense Plus box?  Thanks.

**Comment by MuhammadShaban** [comment]
@opoplawski Thanks for your support
Here is the output of pkg-static info
`aws-sdk-php74-3.103.2          PHP interface for Amazon Web Services (AWS)
bash-5.1.4                     GNU Project's Bourne Again SHell
beep-1.0_1                     Beeps a certain duration and pitch out of the PC Speaker
bind-tools-9.16.11             Command line tools from BIND: delv, dig, host, nslookup...
bsnmp-regex-0.6_2              bsnmpd module allowing creation of counters from log files
bsnmp-ucd-0.4.5                bsnmpd module that implements parts of UCD-SNMP-MIB
bwi-firmware-kmod-3.130.20     Broadcom AirForce IEEE 802.11 Firmware Kernel Module
ca_root_nss-3.58               Root certificate bundle from the Mozilla Project
ccid-1.4.32                    Generic driver for USB CCID and ICCD
check_reload_status-0.0.10_1   run various pfSense scripts on event.
choparp-20150613               Simple proxy arp daemon
cpdup-1.20                     Comprehensive filesystem mirroring and backup program
cpustats-0.1_1                 cpustats
curl-7.74.0                    Command line tool and library for transferring data with URLs
dbus-1.12.20_3                 Message bus system for inter-application communication
devcpu-data-1.37               Intel and AMD CPUs microcode updates
dhcp6-20080615.2_4             KAME DHCP6 client, server, and relay
dhcpleases-0.5_1               read dhpcd.lease file and add it to hosts file
dhcpleases6-0.1_3              read dhpcd6.leases file and trigger command on modification
dmidecode-3.3                  Tool for dumping DMI (SMBIOS) contents in human-readable format
dnsmasq-2.84,1                 Lightweight DNS forwarder, DHCP, and TFTP server
dpinger-3.0                    IP device monitoring tool
expat-2.2.10                   XML 1.0 parser written in C
expiretable-0.6_1              Utility to remove entries from the pf(4) table based on their age
filterdns-2.0_5                filterdns
filterlog-0.1_6                filterlog
gettext-runtime-0.21           GNU gettext runtime libraries and programs
glib-2.66.4_1,1                Some useful routines of C programming (current stable version)
gmp-6.2.1                      Free library for arbitrary precision arithmetic
hostapd-2.9_2                  IEEE 802.11 AP, IEEE 802.1X/WPA/WPA2/EAP/RADIUS Authenticator
icu-68.2,1                     International Components for Unicode (from IBM)
iftop-1.0.p4                   Display bandwidth usage on an interface by host
igmpproxy-0.3,1                Multicast forwarding IGMP proxy
indexinfo-0.3.1                Utility to regenerate the GNU info page index
ipmitool-1.8.18_3              CLI to manage IPMI systems
isc-dhcp44-client-4.4.2_1      The ISC Dynamic Host Configuration Protocol client
isc-dhcp44-relay-4.4.2_1       The ISC Dynamic Host Configuration Protocol relay
isc-dhcp44-server-4.4.2_1      ISC Dynamic Host Configuration Protocol server
json-c-0.15_1                  JSON (JavaScript Object Notation) implementation in C
ldns-1.7.1_2                   Library for programs conforming to DNS RFCs and drafts
libargon2-20190702             Memory hard password hashing program and library
libedit-3.1.20191231,1         Command line editor library
libevent-2.1.12                API for executing callback functions on events or timeouts
libffi-3.3_1                   Foreign Function Interface
libgcrypt-1.8.7                General purpose cryptographic library based on the code from GnuPG
libgpg-error-1.41              Common error values for all GnuPG components
libiconv-1.16                  Character set conversion library
libidn2-2.3.0_1                Implementation of IDNA2008 internationalized domain names
libinotify-20180201_2          Kevent based inotify compatible library
libltdl-2.4.6                  System independent dlopen wrapper
liblz4-1.9.3,1                 LZ4 compression library, lossless and very fast
libmcrypt-2.5.8_3              Multi-cipher cryptographic library (used in PHP)
libnghttp2-1.42.0              HTTP/2.0 C Library
libucl-0.8.1                   Universal configuration library parser
libunistring-0.9.10_1          Unicode string library
libuv-1.40.0                   Multi-platform support library with a focus on asynchronous I/O
libxml2-2.9.10_2               XML parser library for GNOME
libxslt-1.1.34_1               The XSLT C library for GNOME
libzmq4-4.3.1_1                ZeroMQ core library (Version 4)
links-2.20.2_1,1               Lynx-like text WWW browser
lua-resty-core-0.1.21_1        New FFI-based Lua API for OpenResty NGINX Lua modules
lua-resty-lrucache-0.10        Lua-land LRU cache based on the LuaJIT FFI
luajit-openresty-2.1.20201027  Just-In-Time Compiler for Lua (OpenResty branch)
lzo2-2.10_1                    Portable speedy, lossless data compression library
minicron-0.0.2                 very small cron
miniupnpd-2.2.1,1              UPnP IGD implementation which uses pf/ipf
mobile-broadband-provider-info-20190618_1 Service mobile broadband provider database
mpd5-5.9                       Multi-link PPP daemon based on netgraph(4)
mtr-nox11-0.94                 Traceroute and ping in a single network diagnostic tool
nano-5.4                       Nano's ANOther editor, an enhanced free Pico clone
nettle-3.6                     Low-level cryptographic library
nginx-1.18.0_45,2              Robust and small WWW server
norm-1.5r6_1                   NACK-Oriented Reliable Multicast (NORM)
nss_ldap-1.265_13              RFC 2307 NSS module
ntp-4.2.8p15                   The Network Time Protocol Distribution
oniguruma-6.9.6                Regular expressions library compatible with POSIX/GNU/Perl
openldap-client-2.4.57         Open source LDAP client implementation
opensc-0.21.0                  Libraries and utilities to access smart cards
openvpn-2.5.0                  Secure IP/Ethernet tunnel daemon
openvpn-auth-script-1.0.0.3    Generic script-based deferred auth plugin for OpenVPN
pam_ldap-186                   PAM module for authenticating with LDAP
pam_mkhomedir-0.2              Create HOME with a PAM module on demand
pcre-8.44                      Perl Compatible Regular Expressions library
pcre2-10.36                    Perl Compatible Regular Expressions library, version 2
pcsc-lite-1.9.0_1,2            Middleware library to access a smart card using SCard API (PC/SC)
perl5-5.32.1_1                 Practical Extraction and Report Language
pfSense-21.02                  Meta package to install pfSense required ports
pfSense-Status_Monitoring-1.7.11_3 pfSense Status Monitoring
pfSense-base-21.02             pfSense core files
pfSense-default-config-ec2-21.02 pfSense default config (ec2)
pfSense-ec2_setup-0.10         pfSense EC2 setup
pfSense-kernel-pfSense-21.02   pfSense kernel (pfSense)
pfSense-openvpn_connect_profile-0.2_1 pfSense OpenVPN Connect Profile
pfSense-pkg-Cron-0.3.7_5       pfSense package Cron
pfSense-pkg-aws-wizard-0.9     PfSense package AWS VPC VPN Connection Wizard
pfSense-pkg-ipsec-profile-wizard-1.0_2 PfSense package IPsec Export for Apple and Windows devices
pfSense-pkg-mtr-nox11-0.85.6_2 pfSense package mtr-nox11
pfSense-pkg-sudo-0.3_6         pfSense package sudo
pfSense-rc-21.02               pfSense rc script and rc.initial shell
pfSense-repo-21.02             Setup pfSense pkg(8) repositories
pfSense-upgrade-0.92           pfSense upgrade script
pftop-0.7_9                    Utility for real-time display of statistics for pf
php74-7.4.15                   PHP Scripting Language
php74-bcmath-7.4.15            The bcmath shared extension for php
php74-bz2-7.4.15               The bz2 shared extension for php
php74-ctype-7.4.15             The ctype shared extension for php
php74-curl-7.4.15              The curl shared extension for php
php74-dom-7.4.15               The dom shared extension for php
php74-filter-7.4.15            The filter shared extension for php
php74-gettext-7.4.15           The gettext shared extension for php
php74-intl-7.4.15              The intl shared extension for php
php74-json-7.4.15              The json shared extension for php
php74-ldap-7.4.15              The ldap shared extension for php
php74-mbstring-7.4.15          The mbstring shared extension for php
php74-opcache-7.4.15           The opcache shared extension for php
php74-openssl-7.4.15           The openssl shared extension for php
php74-openssl_x509_crl-1.3     PHP Class to create openssl Certificate Revocation List (CRL)
php74-pcntl-7.4.15             The pcntl shared extension for php
php74-pdo-7.4.15               The pdo shared extension for php
php74-pdo_sqlite-7.4.15        The pdo_sqlite shared extension for php
php74-pear-1.10.12             PEAR framework for PHP
php74-pear-Auth_RADIUS-1.1.0_4 PEAR wrapper classes for the RADIUS PECL
php74-pear-Cache_Lite-1.7.16,1 PEAR fast and safe little cache system
php74-pear-Crypt_CHAP-1.5.0    PEAR class for generating CHAP packets
php74-pear-HTTP_Request2-2.3.0,1 PEAR classes providing an easy way to perform HTTP requests
php74-pear-Mail-1.4.1,1        PEAR class that provides multiple interfaces for sending emails
php74-pear-Net_IPv6-1.3.0.b2_2 Check and validate IPv6 addresses
php74-pear-Net_SMTP-1.9.0      PEAR class that provides an implementation of the SMTP protocol
php74-pear-Net_Socket-1.0.14   PEAR Network Socket Interface
php74-pear-Net_URL2-2.2.1      PEAR Class for parsing and handling URL
php74-pear-XML_RPC2-1.1.4      XML-RPC client/server library
php74-pecl-mcrypt-1.0.4        PHP extension for mcrypt, removed in PHP 7.2
php74-pecl-radius-1.4.0.b1     Radius client library for PHP
php74-pecl-rrd-2.0.1_1         PHP bindings to rrd tool system
php74-pecl-zmq-1.1.3_3         PHP bindings for ZeroMQ
php74-pfSense-module-0.69_1    Library for getting useful info
php74-phpseclib-2.0.17         PHP arbitrary-precision integer arithmetic library
php74-posix-7.4.15             The posix shared extension for php
php74-readline-7.4.15          The readline shared extension for php
php74-session-7.4.15           The session shared extension for php
php74-shmop-7.4.15             The shmop shared extension for php
php74-simplepie-1.5.1_1        Simple Atom/RSS parsing library for PHP
php74-simplexml-7.4.15         The simplexml shared extension for php
php74-sockets-7.4.15           The sockets shared extension for php
php74-sqlite3-7.4.15           The sqlite3 shared extension for php
php74-sysvmsg-7.4.15           The sysvmsg shared extension for php
php74-sysvsem-7.4.15           The sysvsem shared extension for php
php74-sysvshm-7.4.15           The sysvshm shared extension for php
php74-tokenizer-7.4.15         The tokenizer shared extension for php
php74-xml-7.4.15               The xml shared extension for php
php74-xmlreader-7.4.15         The xmlreader shared extension for php
php74-xmlwriter-7.4.15         The xmlwriter shared extension for php
php74-zlib-7.4.15              The zlib shared extension for php
pkg-1.16.1                     Package manager
py37-ply-3.11                  Python Lex-Yacc
py37-setuptools-44.0.0         Python packages installer
python37-3.7.9_1               Interpreted object-oriented programming language
qstats-0.2                     read dhpcd.lease file and add it to hosts file
radvd-2.19                     Linux/BSD IPv6 router advertisement daemon
rate-0.9_2                     Traffic analysis command-line utility
readline-8.0.4                 Library for editing command lines as they are typed
rrdtool-1.7.2_4                Round Robin Database Tools
rsync-3.2.3                    Network file distribution/synchronization utility
scponly-4.8.20110526_4         Tiny shell that only permits scp and sftp
smartmontools-7.2              S.M.A.R.T. disk monitoring tools
sqlite3-3.34.0,1               SQL database engine in a C library
ssh_tunnel_shell-0.2_1         SSH tunnel shell
sshguard-2.4.1,1               Protect hosts from brute-force attacks against SSH and other services
strongswan-5.9.1               Open Source IKEv2 IPsec-based VPN solution
sudo-1.9.5p2                   Allow others to run commands as root
telegraf-1.17.0                Time-series data collection
tmux-3.1c                      Terminal Multiplexer
uclcmd-0.1_3                   Command line tool for working with UCL config files
unbound-1.13.0_2               Validating, recursive, and caching DNS resolver
voucher-0.1_2                  Voucher support
vstr-1.0.15_1                  General purpose string library for C
wireguard-tools-20210201       Wireguard tools
wol-0.7.1_4                    Tool to wake up Wake-On-LAN compliant computers
wpa_supplicant-2.9_7           Supplicant (client) for WPA/802.1x protocols
wrapalixresetbutton-0.0.7_1    Utility to detect platform reset button state for use in scripting
xinetd-2.3.15_2                Replacement for inetd with better control and logging
xxhash-0.8.0                   Extremely fast non-cryptographic hash algorithm
zip-3.0_1                      Create/update ZIP files compatible with PKZIP
zstd-1.4.5_1                   Fast real-time compression algorithm
`

**Comment by f-bor** [comment]
the pfSense-base package for pfSense+ 21.02 has a different version than for CE 2.5.0 (I was hoping it would not). I pushed a quick fix in the upstream.

@opoplawski I have assumed that 2.5.0 is the same as 21.02 for now.

**Comment by opoplawski** [comment]
@MuhammadShaban I've pushed that change as well to pfsensible/core master if you'd like to update from git again and test.

**Comment by MuhammadShaban** [comment]
@opoplawski Thanks, it's working now ^_^.

**Comment by muhammadshaban** [comment]
This issue is exists in version 22.01
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: json.decoder.JSONDecodeError: Expecting value: line 2 column 1 (char 1)
fatal: [rajhi_proxy]: FAILED! => {"changed": false, "module_stderr": "Shared connection to ********** closed.\r\n", "module_stdout": "Traceback (most recent call last):\r\n  File \"/home/ec2-user/.ansible/tmp/ansible-tmp-1655673127.682656-140945-161292823035776/AnsiballZ_pfsense_aggregate.py\", line 107, in <module>\r\n    _ansiballz_main()\r\n  File \"/home/ec2-user/.ansible/tmp/ansible-tmp-1655673127.682656-140945-161292823035776/AnsiballZ_pfsense_aggregate.py\", line 99, in _ansiballz_main\r\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\r\n  File \"/home/ec2-user/.ansible/tmp/ansible-tmp-1655673127.682656-140945-161292823035776/AnsiballZ_pfsense_aggregate.py\", line 47, in invoke_module\r\n    runpy.run_module(mod_name='ansible_collections.pfsensible.core.plugins.modules.pfsense_aggregate', init_globals=dict(_module_fqn='ansible_collections.pfsensible.core.plugins.modules.pfsense_aggregate', _modlib_path=modlib_path),\r\n  File \"/usr/local/lib/python3.8/runpy.py\", line 207, in run_module\r\n    return _run_module_code(code, init_globals, run_name, mod_spec)\r\n  File \"/usr/local/lib/python3.8/runpy.py\", line 97, in _run_module_code\r\n    _run_code(code, mod_globals, init_globals,\r\n  File \"/usr/local/lib/python3.8/runpy.py\", line 87, in _run_code\r\n    exec(code, run_globals)\r\n  File \"/tmp/ansible_pfsensible.core.pfsense_aggregate_payload_qzpe9v1u/ansible_pfsensible.core.pfsense_aggregate_payload.zip/ansible_collections/pfsensible/core/plugins/modules/pfsense_aggregate.py\", line 1103, in <module>\r\n  File \"/tmp/ansible_pfsensible.core.pfsense_aggregate_payload_qzpe9v1u/ansible_pfsensible.core.pfsense_aggregate_payload.zip/ansible_collections/pfsensible/core/plugins/modules/pfsense_aggregate.py\", line 1088, in main\r\n  File \"/tmp/ansible_pfsensible.core.pfsense_aggregate_payload_qzpe9v1u/ansible_pfsensible.core.pfsense_aggregate_payload.zip/ansible_collections/pfsensible/core/plugins/modules/pfsense_aggregate.py\", line 623, in __init__\r\n  File \"/tmp/ansible_pfsensible.core.pfsense_aggregate_payload_qzpe9v1u/ansible_pfsensible.core.pfsense_aggregate_payload.zip/ansible_collections/pfsensible/core/plugins/module_utils/vlan.py\", line 73, in __init__\r\n  File \"/tmp/ansible_pfsensible.core.pfsense_aggregate_payload_qzpe9v1u/ansible_pfsensible.core.pfsense_aggregate_payload.zip/ansible_collections/pfsensible/core/plugins/module_utils/pfsense.py\", line 606, in php\r\n  File \"/usr/local/lib/python3.8/json/__init__.py\", line 357, in loads\r\n    return _default_decoder.decode(s)\r\n  File \"/usr/local/lib/python3.8/json/decoder.py\", line 337, in decode\r\n    obj, end = self.raw_decode(s, idx=_w(s, 0).end())\r\n  File \"/usr/local/lib/python3.8/json/decoder.py\", line 355, in raw_decode\r\n    raise JSONDecodeError(\"Expecting value\", s, err.value) from None\r\njson.decoder.JSONDecodeError: Expecting value: line 2 column 1 (char 1)\r\n", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}

**Comment by muhammadshaban** [comment]
Here is the output of pkg-static info

aws-sdk-php74-3.185.15         PHP interface for Amazon Web Services (AWS)
bash-5.1.12                    GNU Project's Bourne Again SHell
beep-1.0_1                     Beeps a certain duration and pitch out of the PC Speaker
bind-tools-9.16.23             Command line tools from BIND: delv, dig, host, nslookup...
bsnmp-regex-0.6_2              bsnmpd module allowing creation of counters from log files
bsnmp-ucd-0.4.5                bsnmpd module that implements parts of UCD-SNMP-MIB
bwi-firmware-kmod-3.130.20     Broadcom AirForce IEEE 802.11 Firmware Kernel Module
ca_root_nss-3.71               Root certificate bundle from the Mozilla Project
ccid-1.4.36                    Generic driver for USB CCID and ICCD
check_reload_status-0.0.11     run various pfSense scripts on event.
choparp-20150613               Simple proxy arp daemon
cpdup-1.22                     Comprehensive filesystem mirroring and backup program
cpustats-0.1_1                 cpustats
curl-7.80.0                    Command line tool and library for transferring data with URLs
cyrus-sasl-2.1.27_2            RFC 2222 SASL (Simple Authentication and Security Layer)
dbus-1.12.20_5                 Message bus system for inter-application communication
devcpu-data-20211109           AMD and Intel CPUs microcode updates
devcpu-data-amd-20211115       AMD CPUs microcode updates
devcpu-data-intel-20210608     Intel CPU microcode updates
dhcp6-20080615.2_4             KAME DHCP6 client, server, and relay
dhcpleases-0.5_1               read dhpcd.lease file and add it to hosts file
dhcpleases6-0.1_3              read dhpcd6.leases file and trigger command on modification
dmidecode-3.3                  Tool for dumping DMI (SMBIOS) contents in human-readable format
dnsmasq-2.86,1                 Lightweight DNS forwarder, DHCP, and TFTP server
dpinger-3.0                    IP device monitoring tool
expat-2.4.1                    XML 1.0 parser written in C
expiretable-0.6_2              Utility to remove entries from the pf(4) table based on their age
filterdns-2.0_5                filterdns
filterlog-0.1_9                filterlog
gettext-runtime-0.21           GNU gettext runtime libraries and programs
glib-2.70.2,2                  Some useful routines of C programming (current stable version)
hostapd-2.9_4                  IEEE 802.11 AP, IEEE 802.1X/WPA/WPA2/EAP/RADIUS Authenticator
icu-70.1_1,1                   International Components for Unicode (from IBM)
iftop-1.0.p4                   Display bandwidth usage on an interface by host
igmpproxy-0.3,1                Multicast forwarding IGMP proxy
indexinfo-0.3.1                Utility to regenerate the GNU info page index
ipmitool-1.8.18_3              CLI to manage IPMI systems
isc-dhcp44-client-4.4.2P1      The ISC Dynamic Host Configuration Protocol client
isc-dhcp44-relay-4.4.2P1       The ISC Dynamic Host Configuration Protocol relay
isc-dhcp44-server-4.4.2P1_1    ISC Dynamic Host Configuration Protocol server
jansson-2.14                   C library for encoding, decoding, and manipulating JSON data
json-c-0.15_1                  JSON (JavaScript Object Notation) implementation in C
ldns-1.7.1_2                   Library for programs conforming to DNS RFCs and drafts
libargon2-20190702             Memory hard password hashing program and library
libedit-3.1.20210216,1         Command line editor library
libevent-2.1.12                API for executing callback functions on events or timeouts
libffi-3.3_1                   Foreign Function Interface
libgcrypt-1.9.4                General purpose cryptographic library based on the code from GnuPG
libgpg-error-1.43              Common error values for all GnuPG components
libiconv-1.16                  Character set conversion library
libidn2-2.3.2                  Implementation of IDNA2008 internationalized domain names
libinotify-20180201_2          Kevent based inotify compatible library
libltdl-2.4.6                  System independent dlopen wrapper
liblz4-1.9.3,1                 LZ4 compression library, lossless and very fast
libmcrypt-2.5.8_3              Multi-cipher cryptographic library (used in PHP)
libnghttp2-1.46.0              HTTP/2.0 C Library
libssh2-1.9.0_3,3              Library implementing the SSH2 protocol
libucl-0.8.1                   Universal configuration library parser
libunistring-0.9.10_1          Unicode string library
libuv-1.42.0                   Multi-platform support library with a focus on asynchronous I/O
libxml2-2.9.12                 XML parser library for GNOME
libxslt-1.1.34_2               XML stylesheet transformation library
links-2.20.2_1,1               Lynx-like text WWW browser
lua-resty-core-0.1.22          New FFI-based Lua API for OpenResty NGINX Lua modules
lua-resty-lrucache-0.11        Lua-land LRU cache based on the LuaJIT FFI
luajit-openresty-2.1.20210510  Just-In-Time Compiler for Lua (OpenResty branch)
lzo2-2.10_1                    Portable speedy, lossless data compression library
minicron-0.0.2                 very small cron
miniupnpd-2.2.1_1,1            UPnP IGD implementation which uses pf/ipf
mobile-broadband-provider-info-20210805 Service mobile broadband provider database
mpd5-5.9_6                     Multi-link PPP daemon based on netgraph(4)
mpdecimal-2.5.1                C/C++ arbitrary precision decimal floating point libraries
mtr-nox11-0.94_1               Traceroute and ping in a single network diagnostic tool
nano-5.9                       Nano's ANOther editor, an enhanced free Pico clone
nginx-1.20.2_1,2               Robust and small WWW server
nss_ldap-1.265_14              RFC 2307 NSS module
ntp-4.2.8p15_3                 The Network Time Protocol Distribution
oniguruma-6.9.7.1              Regular expressions library compatible with POSIX/GNU/Perl
openldap24-client-2.4.59_4     Open source LDAP client implementation
opensc-0.22.0                  Libraries and utilities to access smart cards
openvpn-2.5.4_1                Secure IP/Ethernet tunnel daemon
openvpn-auth-script-1.0.0.3    Generic script-based deferred auth plugin for OpenVPN
pam_ldap-186_1                 PAM module for authenticating with LDAP
pam_mkhomedir-0.2              Create HOME with a PAM module on demand
pcre-8.45                      Perl Compatible Regular Expressions library
pcre2-10.39                    Perl Compatible Regular Expressions library, version 2
pcsc-lite-1.9.4,2              Middleware library to access a smart card using SCard API (PC/SC)
perl5-5.32.1_1                 Practical Extraction and Report Language
pfSense-22.01                  Meta package to install pfSense required ports
pfSense-Status_Monitoring-1.7.11_4 pfSense Status Monitoring
pfSense-base-22.01             pfSense core files
pfSense-default-config-ec2-22.01 pfSense default config (ec2)
pfSense-ec2_setup-0.10         pfSense EC2 setup
pfSense-kernel-pfSense-22.01   pfSense kernel (pfSense)
pfSense-openvpn_connect_profile-0.2_1 pfSense OpenVPN Connect Profile
pfSense-pkg-Cron-0.3.7_5       pfSense package Cron
pfSense-pkg-aws-wizard-0.10    PfSense package AWS VPC VPN Connection Wizard
pfSense-pkg-ipsec-profile-wizard-1.0_4 PfSense package IPsec Export for Apple and Windows devices
pfSense-pkg-mtr-nox11-0.85.6_2 pfSense package mtr-nox11
pfSense-pkg-sudo-0.3_6         pfSense package sudo
pfSense-rc-22.01               pfSense rc script and rc.initial shell
pfSense-repo-22.01_3           Setup pfSense pkg(8) repositories
pfSense-upgrade-1.0_12         pfSense upgrade script
pftop-0.7_9                    Utility for real-time display of statistics for pf
php74-7.4.26                   PHP Scripting Language
php74-bcmath-7.4.26            The bcmath shared extension for php
php74-bz2-7.4.26               The bz2 shared extension for php
php74-ctype-7.4.26             The ctype shared extension for php
php74-curl-7.4.26              The curl shared extension for php
php74-dom-7.4.26               The dom shared extension for php
php74-filter-7.4.26            The filter shared extension for php
php74-gettext-7.4.26           The gettext shared extension for php
php74-intl-7.4.26              The intl shared extension for php
php74-json-7.4.26              The json shared extension for php
php74-ldap-7.4.26              The ldap shared extension for php
php74-mbstring-7.4.26          The mbstring shared extension for php
php74-opcache-7.4.26           The opcache shared extension for php
php74-openssl-7.4.26           The openssl shared extension for php
php74-openssl_x509_crl-1.3     PHP Class to create openssl Certificate Revocation List (CRL)
php74-pcntl-7.4.26             The pcntl shared extension for php
php74-pdo-7.4.26               The pdo shared extension for php
php74-pdo_sqlite-7.4.26        The pdo_sqlite shared extension for php
php74-pear-1.10.12             PEAR framework for PHP
php74-pear-Auth_RADIUS-1.1.0_4 PEAR wrapper classes for the RADIUS PECL
php74-pear-Cache_Lite-1.8.3,1  Fast and Safe little cache system
php74-pear-Crypt_CHAP-1.5.0    PEAR class for generating CHAP packets
php74-pear-HTTP_Request2-2.5.0,1 PEAR classes providing an easy way to perform HTTP requests
php74-pear-Mail-1.4.1,1        PEAR class that provides multiple interfaces for sending emails
php74-pear-Net_IPv6-1.3.0.b2_2 Check and validate IPv6 addresses
php74-pear-Net_SMTP-1.10.0     PEAR class that provides an implementation of the SMTP protocol
php74-pear-Net_Socket-1.2.2    PEAR Network Socket Interface
php74-pear-Net_URL2-2.2.1      PEAR Class for parsing and handling URL
php74-pear-XML_RPC2-1.1.4      XML-RPC client/server library
php74-pecl-mcrypt-1.0.4        PHP extension for mcrypt, removed in PHP 7.2
php74-pecl-radius-1.4.0b1_1    Radius client library for PHP
php74-pecl-rrd-2.0.1_1         PHP bindings to rrd tool system
php74-pfSense-module-0.76      Library for getting useful info
php74-phpseclib-2.0.17         PHP arbitrary-precision integer arithmetic library
php74-posix-7.4.26             The posix shared extension for php
php74-readline-7.4.26          The readline shared extension for php
php74-session-7.4.26           The session shared extension for php
php74-shmop-7.4.26             The shmop shared extension for php
php74-simplepie-1.5.1_1        Simple Atom/RSS parsing library for PHP
php74-simplexml-7.4.26         The simplexml shared extension for php
php74-sockets-7.4.26           The sockets shared extension for php
php74-sqlite3-7.4.26           The sqlite3 shared extension for php
php74-sysvmsg-7.4.26           The sysvmsg shared extension for php
php74-sysvsem-7.4.26           The sysvsem shared extension for php
php74-sysvshm-7.4.26           The sysvshm shared extension for php
php74-tokenizer-7.4.26         The tokenizer shared extension for php
php74-xml-7.4.26               The xml shared extension for php
php74-xmlreader-7.4.26         The xmlreader shared extension for php
php74-xmlwriter-7.4.26         The xmlwriter shared extension for php
php74-zlib-7.4.26              The zlib shared extension for php
pkg-1.17.5_2                   Package manager
py38-libzfs-1.1.2021100100     Python libzfs bindings
py38-ply-3.11                  Python Lex-Yacc
py38-setuptools-57.0.0         Python packages installer
python38-3.8.12_1              Interpreted object-oriented programming language
qstats-0.2                     read dhpcd.lease file and add it to hosts file
radvd-2.19_2                   Linux/BSD IPv6 router advertisement daemon
rate-0.9_2                     Traffic analysis command-line utility
readline-8.1.1                 Library for editing command lines as they are typed
rrdtool-1.7.2_4                Round Robin Database Tools
rsync-3.2.3_1                  Network file distribution/synchronization utility
scponly-4.8.20110526_5         Tiny shell that only permits scp and sftp
smartmontools-7.2_3            S.M.A.R.T. disk monitoring tools
sqlite3-3.35.5_4,1             SQL database engine in a C library
ssh_tunnel_shell-0.2_1         SSH tunnel shell
sshguard-2.4.2_1,1             Protect hosts from brute-force attacks against SSH and other services
strongswan-5.9.4               Open Source IKEv2 IPsec-based VPN solution
sudo-1.9.8p2                   Allow others to run commands as root
telegraf-1.20.4                Time-series data collection
tmux-3.2a                      Terminal Multiplexer
uclcmd-0.1_3                   Command line tool for working with UCL config files
unbound-1.13.2                 Validating, recursive, and caching DNS resolver
voucher-0.1_2                  Voucher support
vstr-1.0.15_1                  General purpose string library for C
wol-0.7.1_4                    Tool to wake up Wake-On-LAN compliant computers
wpa_supplicant-2.9_11          Supplicant (client) for WPA/802.1x protocols
wrapalixresetbutton-0.0.11     Utility to detect platform reset button state for use in scripting
xinetd-2.3.15_2                Replacement for inetd with better control and logging
xxhash-0.8.0                   Extremely fast non-cryptographic hash algorithm
zip-3.0_1                      Create/update ZIP files compatible with PKZIP
zstd-1.5.0                     Fast real-time compression algorithm

**Comment by muhammadshaban** [comment]
php error message

PHP ERROR: Type: 1, File: Standard input code, Line: 2, Message: Uncaught Error: Call to undefined function is_jumbo_capable() in Standard input code:2

**Comment by muhammadshaban** [comment]
This solution fix the issue #34
